name: GBC
pygments: true
sass:
   syntax:  scss
   style:   expanded
assets:
   cache: false
   gzip: false
   cachebust: none
   sources:
   - _assets/images          
   - _assets/stylesheets          
   - _assets/javascripts
   #js_compressor:  uglify
   #css_compressor: sass